export const studentDefaultValues = {
  accountType: "student",
  email: "",
  password: "",
  confirmPassword: "",
  firstName: "",
  lastName: "",
  birthDate: "",
  gender: "",
  major: "",
  startingDate: "",
  expectedGradDate: "",
  country: "",
  studentSkills: [],
  studentCV: "",
  studentBio: "",
};

export const providerDefaultValues = {
  accountType: "provider",
  email: "",
  password: "",
  confirmPassword: "",
  name: "",
  estDate: "",
  country: "",
  industry: "",
  about: "",
  file: null,
};
